FROM debian:12-slim
RUN apt-get update && apt-get install -y --no-install-recommends \
      default-mysql-client postgresql-client ca-certificates \
    && rm -rf /var/lib/apt/lists/*
COPY dbtote /usr/local/bin/dbtote
ENTRYPOINT ["dbtote"]
